name: airbnb-price-prediction
channels:
    - conda-forge
dependencies:
    - python=3.7
    - numpy=1.16.5
    - pandas=1.0.3
    - pandas-profiling=2.8.0
    - ipykernel=5.3.0
    - matplotlib=3.2.1
    - seaborn=0.10.1
    - scikit-learn=0.23.1
    - python-geohash=0.8.5
